# Generated by Django 5.0.6 on 2024-06-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(default='Sin comuna', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Sin comuna', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.CharField(default='Sin comuna', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='Sin comuna', max_length=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
