# Generated by Django 5.0.6 on 2024-07-01 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_region_alter_imagenproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El RUT debe ingresarse en el formato: 'XX.XXX.XXX-X'.", regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9Kk]$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ingresarse en el formato: '+56912345678'. 9 dígitos después del código de país '+56'.", regex='^\\+56\\d{9}$')]),
        ),
    ]
